# Generated by Django 3.1.1 on 2020-09-24 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinates',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='coordinates',
            name='title',
        ),
    ]
